# Generated by Django 3.2 on 2022-10-30 10:35

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20221029_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Shows whether the category is published (default is True)')),
                ('name', models.CharField(help_text='The name of the category. Max length is 150 symbols', max_length=150)),
                ('slug', models.SlugField(help_text='The slug (unique id). Max length is 200 symbols. Only contains latin letters, numbers, and symbols: - _', max_length=200, unique=True)),
                ('weight', models.PositiveSmallIntegerField(default=100, help_text='The weight of the category. Should be in range [1, 32766]. Default is 100.')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the tag. Max length is 150 symbols', max_length=150)),
                ('is_published', models.BooleanField(default=True, help_text='Shows whether the tag is published (default is True)')),
                ('slug', models.SlugField(help_text='The slug (unique id). Max length is 200 symbols. Only contains latin letters, numbers, and symbols: - _', max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.TextField(default='default_text', help_text="The information about the item. Must contain 'превосходно' or 'роскошно'"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Shows whether the item is published (default is True)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='The name of the item. Max length is 150 symbols', max_length=150),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='catalog.Tag'),
        ),
    ]
