# Generated by Django 3.2 on 2022-10-30 11:31

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20221030_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text="The information about the item. Must contain 'превосходно' or 'роскошно'", validators=[catalog.validators.validate_must_be_param]),
        ),
    ]
