# Generated by Django 3.2 on 2022-11-01 19:12

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_item_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Показывает, видна ли запись на сайте (по умолчанию ДА)', verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Название. Максимальная длина - 150 символов', max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Уникальный идентификатор. Максимальная длина - 200 символов. Может содержать только латинские буквы, цифры, дефис и нижнее подчеркивание (- и _). Пример: My-Very-First-Model-1', max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.PositiveSmallIntegerField(default=100, help_text='Вес категории. Должен находиться в пределах [1, 32766]. По умолчанию 100.', verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='К какой категории относится товар?', on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Показывает, видна ли запись на сайте (по умолчанию ДА)', verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Название. Максимальная длина - 150 символов', max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(help_text='Теги к товару', to='catalog.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text="Информация о товаре. Должна содержать слова 'превосходно' или 'роскошно'", validators=[catalog.validators.validate_must_be_param], verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Показывает, видна ли запись на сайте (по умолчанию ДА)', verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Название. Максимальная длина - 150 символов', max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Уникальный идентификатор. Максимальная длина - 200 символов. Может содержать только латинские буквы, цифры, дефис и нижнее подчеркивание (- и _). Пример: My-Very-First-Model-1', max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
