# Generated by Django 3.2.4 on 2022-11-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_item_text'),
        ('catalog', '0013_alter_item_text'),
    ]

    operations = [
    ]
