# Generated by Django 3.2.4 on 2022-11-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_item_text'),
        ('catalog', '0014_merge_0010_alter_item_text_0013_alter_item_text'),
    ]

    operations = [
    ]
