# Generated by Django 3.2.4 on 2022-11-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_merge_20221120_1959'),
        ('catalog', '0016_alter_item_text'),
    ]

    operations = [
    ]
