# Generated by Django 3.2.4 on 2022-12-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_item_text'),
        ('catalog', '0021_alter_item_text'),
    ]

    operations = [
    ]
